Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
      Policies: 
        - PolicyName: MyCoolPolicy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
                - Sid: IamListAccess
                  Effect: Allow
                  Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                  Resource: '*'
      UserName: 'my-cool-user'
  MyInlinePolicy:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-iam-policy.html#aws-resource-iam-policy--examples
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MyInlinePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'
      Users: 
        - !Ref MyUser

  MySecondInlinePolicy:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-iam-userpolicy.html#aws-resource-iam-userpolicy--examples
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MySecondInlinePolicy
      UserName: !Ref MyUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'

