AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create a role to assume and create a resources to have access to 

Parameters:
  BucketName:
    Type: String
    Default: "frank-example-sts-solution-architect"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  STSRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: "arn:aws:iam::444051961052:user/Bob"
                # Service:
                #   - s3.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        # ManagedPolicyArns:
        #   - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        Path: /
        Policies:
          - PolicyName: s3access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:  
                - Effect: Allow
                  Action:
                    - 's3:List*'
                  Resource:
                    - !Sub 'arn:aws:s3:::*'

                - Effect: Allow
                  Action: '*'
                  Resource: [
                    !Sub 'arn:aws:s3:::${BucketName}',
                    !Sub 'arn:aws:s3:::${BucketName}/*'
                  ]

